# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Importing 'capistrano/rails' fails if you're using an API-only Rails project that doesn't have Sprockets set up
# causing an "Don't know how to build task 'assets:precompile'" error.
# 'capistrano/rails' actually just imports 'capistrano/rails/migrations' and 'capistrano/rails/assets'
# source: https://stackoverflow.com/questions/41052204/deploy-raise-error-dont-know-how-to-build-task-assetsprecompile-capistran
#  Uncomment for API projects
# require 'capistrano/rails/migrations'
# Comment out for API projects
require 'capistrano/rails'

require "capistrano/bundler"
require 'capistrano/rvm'
require 'capistrano/puma'

require "whenever/capistrano"

# Update sitemap https://github.com/kjvarga/sitemap_generator#deployments--capistrano
require 'capistrano/sitemap_generator'

# Fix for Capistrano >= 3.15.0 & Puma >= 5.0
# Puma 5 stopped supporting daemonized puma in favor of SystemD
# We're still using Puma 4 to be able to use the daemonized version
# Source: https://stackoverflow.com/a/67590076/2565681
# More info: https://github.com/seuros/capistrano-puma
install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Daemon  # If you using puma daemonized (not supported in Puma 5+)

set :rvm_type, :user
set :rvm_ruby_version, '$RUBY_VERSION'

# If we get an error `rvm stdout: bash: /home/rails/.rvm/bin/rvm: No such file or directory`
# we need to run:
# > Then run the following commands on your Production machine in your SSH user's home directory:
# > mkdir .rvm && mkdir .rvm/bin
# > ln -s /usr/share/rvm/bin/rvm .rvm/bin/rvm
#
# Source: https://www.matthewhoelter.com/2020/11/10/deploying-ruby-on-rails-for-ubuntu-2004.html

# If you are using rbenv add these lines:
# require 'capistrano/rbenv'
# set :rbenv_type, :user
# set :rbenv_ruby, '2.6.1'

# If you are using rvm add these lines:

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
