# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Importing 'capistrano/rails' fails if you're using an API-only Rails project that doesn't have Sprockets set up
# causing an "Don't know how to build task 'assets:precompile'" error.
# 'capistrano/rails' actually just imports 'capistrano/rails/migrations' and 'capistrano/rails/assets'
# source: https://stackoverflow.com/questions/41052204/deploy-raise-error-dont-know-how-to-build-task-assetsprecompile-capistran
require 'capistrano/rails/migrations'

require "capistrano/bundler"
require 'capistrano/rvm'
require 'capistrano/puma'

install_plugin Capistrano::Puma

set :rvm_type, :user
set :rvm_ruby_version, '$RUBY_VERSION'

# If you are using rbenv add these lines:
# require 'capistrano/rbenv'
# set :rbenv_type, :user
# set :rbenv_ruby, '2.6.1'

# If you are using rvm add these lines:

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
